language: go
go:
- 1.11.x
go_import_path: "$HOME/go/src/public/public-golang-restapi-app"
before_install:
  - go get github.com/tools/godep
  - go get github.com/gorilla/websocket
deploy:
  provider: heroku
  app: public-go-restapi-prod
  on:
    repo: ncmd/public-golang-restapi-app
    branch: master
  api_key:
    secure: KqsG3QPSW69+whujHmqhKu1Hjt3eESVQhLDWDEifj8YHxM1WKiXTW8Yz2tFgqKmDZfrZziwJZadL/ypq7MMdNDix5ASoGmZgReXy0So8c89nKUz6HLdZExDnWU6VcAR46NUO+OLpiMWIOIyrAr3ARlURjLWBIzaQtww/3129jtqOIYXQXMqlYLda5Z5E/LnsLAwT5A6RiuLq5KLQqolFSvdM6aguhWnma7dwRUYYJB31w7ruUVjZx8VPMArN0UNETJhEVq1NvycUQ6SOCwmV7V0pChR90Nqy9wyZhDCxGVk4ISJvYOH4ByKSqdKF5LdwrAQAWHOmD4pYKAzDq2Z5GDLGiITr4CBw04ROL/D9qeIm0d6QExVjbyY43Qswb/iY2zeFPZoNyGvqjC5xdDsFwjPxe7Yn6uqjlf+zstmZPhVIC125UKjWL9fb0gIQ1U6N2tk9meSd+MpY7ZNfUyWrw8wfA/jeYW9ZuY39kHbqXGacTfcfbX5Vbcej/KdMo8xXFPsabDJ1AEu8b9ACbeexXgLo+H+nXwxalXc8394u9XTZfrvdO4brZa6yPxNu1grHqWLZv9/lmNoll/IBlJSZM8PFy91wA3dcVW3q2a3jdFiDBEt/Aeq/eHPRU8ae7ZkH42zCwDPeNj5dlxFlkZuuzvOiygIC8/s0Pt5IAq3/T1k=
env:
  APP_ENV: prod
